Updates

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,11 +1,36 @@
 #!/bin/bash
-# The actual `bin/compile` code lives in `bin/support/ruby_compile`. This file 
+# The actual `bin/compile` code lives in `bin/support/ruby_compile`. This file
 # instead bootstraps the ruby needed and then executes `bin/support/ruby_compile`
 
 BIN_DIR=$(cd $(dirname $0); pwd)
 BUILDPACK_DIR=$(dirname $BIN_DIR)
+new_header="#!/app/web/vendor/ruby-2.3.1/bin/ruby"
 
 source "$BIN_DIR/support/bash_functions.sh"
 heroku_buildpack_ruby_install_ruby "$BIN_DIR" "$BUILDPACK_DIR"
 
 $heroku_buildpack_ruby_dir/bin/ruby $BIN_DIR/support/ruby_compile $@
+
+
+#sed -i.bak 1 s/^.*$/$new_header/ $1/web/vendor/ruby-2.3.1/bin/rake
+#sed -i.bak "1 s/#!/app/vendor/ruby-2.3.1/bin/ruby/$new_header/" "$1/web/vendor/ruby-2.3.1/bin/rake"
+#sed -i.bak "1 s/^.*$/$new_header/" "$1/web/vendor/ruby-2.3.1/bin/rake"
+
+cat "$1/web/vendor/ruby-2.3.1/bin/rake"
+
+sed -i "1 s/^.*$/\#\!\/app\/web\/vendor\/ruby-2.3.1\/bin\/ruby/" "$1/web/vendor/ruby-2.3.1/bin/rake"
+
+cat "$1/web/vendor/ruby-2.3.1/bin/rake"
+
+
+
+cp -r "$1/web/.profile.d" "$1/"
+
+if [ $? -eq 0 ]; then
+  rm -rf "$1/web/.profile.d"
+  exit 0
+else
+  echo ".profile.d is not found into /web folder"
+  exit 1
+fi
+
